
# Configura\u00E7\u00E3o do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/seplag
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

#Configura\u00E7\u00E3o do Hibernate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#spring.sql.init.data-locations=classpath:script.sql

# Configura\u00E7\u00E3o do MinIO
minio.url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=admin123
minio.bucketName=servidores

#Configura\u00E7\u00E3o do Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

#Max size upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


