
# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/seplag
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuração do Hibernate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
#spring.sql.init.data-locations=classpath:script.sql

# Configuração do MinIO
minio.url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=admin123
minio.bucketName=servidores

#Configuração do Swagger
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true

