
# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seplag
spring.datasource.username=joao
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuração do MinIO
minio.url=http://localhost:9000
minio.accessKey=admin
minio.secretKey=admin123
minio.bucketName=minha-pasta

# Configuração do Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuração do JWT
jwt.secret=mysecretkey
jwt.expiration=86400000 # 1 dia
